stages:
  - build
  - deploy

build-job:
  stage: build
  tags:
    - datthai # Tag của runner SSH
  script:
    - echo "Navigating to project directory: C:/OJT/team03"
    - cd C:/OJT/team03
    - echo "Pulling latest code from main branch..."
    - git config --global credential.helper store
    - echo "https://$GITLAB_USER:$GITLAB_PAT@git.fa.edu.vn" > ~/.git-credentials
    - git pull origin main
    - echo "Restoring .NET packages..."
    - dotnet restore
    - echo "Building and publishing the project..."
    - dotnet publish -c Release -o ./publish --no-restore
  only:
    - main

deploy-job:
  stage: deploy
  tags:
    - datthai # Tag của runner SSH
  needs:
    - build-job # Chờ build xong mới deploy
  script:
    - echo "Restarting the application service..."
    - Restart-Service -Name "MovieTheaterService" # Tên service trên máy Windows
    - echo "Deployment successful!"
  only:
    - main