before_script:
  - dotnet --version
  - dotnet restore
  - git config --global credential.helper store
  - echo "https://$GITLAB_USER:$GITLAB_PAT@git.fa.edu.vn" > ~/.git-credentials

stages:
  - build-n-test
  - deploy

build-and-test-job:
  stage: build-n-test
  tags:
    - datthai
  script:
    - echo "Compiling the code..."
    - dotnet build --no-restore
    - echo "Compile completed build."
    - echo "Running unit tests... This will take about 60 seconds."
    - dotnet test --no-restore

# Nếu muốn có thêm job test riêng, có thể bỏ comment phần này
#unit-test-job:
#  stage: test
#  script:
#    - echo "Running unit tests... This will take about 60 seconds."
#    - echo "Code coverage is 90%"

deploy-job:
  stage: deploy
  tags:
    - datthai
  script:
    - echo "Deploying application..."
    - cloudflared tunnel run team_3_NET_05
    - dotnet run --project MovieTheater.csproj --urls "http://127.0.0.1:7201"
    - echo "Application successfully deployed."