stages:
  - build
  - deploy

build-job:
  stage: build
  tags:
    - datthai
  before_script:
    # Xóa tất cả các credential đã được cache bởi Git
    - git config --global --unset-all credential.helper
    # Thiết lập lại credential helper
    - git config --global credential.helper store
    - echo "https://$GITLAB_USER:$GITLAB_PAT@git.fa.edu.vn" > ~/.git-credentials
  script:
    - echo "Navigating to project directory..."
    - cd $CI_PROJECT_DIR
    - echo "Pulling latest code..."
    - git pull origin main
    - echo "Restoring packages..."
    - dotnet restore
    - echo "Building and publishing project..."
    - dotnet publish -c Release -o ./publish --no-restore
  only:
    - main

deploy-job:
  stage: deploy
  tags:
    - datthai
  needs:
    - build-job
  script:
    - echo "Restarting the application service..."
    - Restart-Service -Name "MovieTheaterService"
    - echo "Deployment successful!"
  only:
    - main