name: Debug Test

on:
  push:
    branches:
      - quality-gate
  pull_request:
    branches:
      - quality-gate

jobs:
  debug:
    name: Debug Test Issues
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Check .NET version
        run: dotnet --version
        
      - name: List project files
        shell: powershell
        run: |
          Write-Host "Project structure:"
          Get-ChildItem -Recurse -Name "*.csproj"
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build with verbose
        run: dotnet build --no-restore --verbosity normal
        
      - name: List test projects
        run: dotnet test --list-tests
        
      - name: Run tests with detailed output
        run: dotnet test MovieTheater.Tests --logger "console;verbosity=detailed" --configuration Release
        
      - name: Check test results directory
        shell: powershell
        run: |
          Write-Host "Current directory: $(Get-Location)"
          Write-Host "TestResults exists: $(Test-Path 'TestResults')"
          if (Test-Path "TestResults") {
            Get-ChildItem -Path TestResults -Recurse | ForEach-Object {
              Write-Host "Found: $($_.FullName)"
            }
          }
          
      - name: Run coverage test separately
        run: dotnet test MovieTheater.Tests --collect:"XPlat Code Coverage" --results-directory "TestResults" --configuration Release --logger "console;verbosity=detailed"
        
      - name: Final check
        shell: powershell
        run: |
          Write-Host "Final TestResults check:"
          if (Test-Path "TestResults") {
            Get-ChildItem -Path TestResults -Recurse | ForEach-Object {
              Write-Host "Final: $($_.FullName)"
            }
          } else {
            Write-Host "TestResults still not found"
          } 