name: Test Coverage

on:
  push:
    branches:
      - main
      - develop
      - quality-gate
  pull_request:
    branches:
      - main
      - develop
      - quality-gate

jobs:
  test-coverage:
    name: Test Coverage
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Run tests with coverage
        shell: powershell
        run: |
          dotnet test MovieTheater.Tests --collect:"XPlat Code Coverage" --results-directory "TestResults" --configuration Release --logger "console;verbosity=minimal"
          
      - name: Check coverage files
        shell: powershell
        run: |
          Write-Host "Checking for coverage files..."
          Get-ChildItem -Path TestResults -Recurse -Filter "*.xml" | ForEach-Object {
            Write-Host "Found coverage file: $($_.FullName)"
          }
          
      - name: Install ReportGenerator
        shell: powershell
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          
      - name: Generate HTML coverage report
        shell: powershell
        run: |
          if (Test-Path "TestResults\**\coverage.cobertura.xml") {
            reportgenerator -reports:"TestResults/**/coverage.cobertura.xml" -targetdir:"coverage-report" -reporttypes:Html;TextSummary -sourcedirs:"." -verbosity:Normal
            Write-Host "Coverage report generated successfully"
          } else {
            Write-Host "No coverage files found"
            exit 1
          }
          
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage-report/
          retention-days: 30
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: TestResults/
          retention-days: 30 