name: Test SonarQube

on:
  push:
    branches:
      - quality-gate

jobs:
  test:
    name: Test SonarQube Configuration
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Check SonarQube config
        shell: powershell
        run: |
          Write-Host "Checking sonar-project.properties..."
          if (Test-Path "sonar-project.properties") {
            Get-Content "sonar-project.properties"
          } else {
            Write-Host "sonar-project.properties not found!"
          }
          
      - name: Install SonarQube Scanner
        shell: powershell
        run: |
          dotnet tool install --global dotnet-sonarscanner
          
      - name: Test SonarQube Scanner
        shell: powershell
        run: |
          Write-Host "Testing SonarQube scanner..."
          dotnet sonarscanner --version 